<?php
namespace SlmGoogleAnalytics\Analytics;

use SlmGoogleAnalytics\Analytics\Collection as Collection;
use SlmGoogleAnalytics\Analytics\Tracker as Tracker;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-15 at 13:54:17.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Collection
     */
    protected $collection;

    /**
     * @var Collection > Tracker
     */
    protected $child_tracker;

    /**
     * @var Tracker
     */
    protected $tracker;

    protected function setUp()
    {
        $this->collection = new Collection;
        $this->child_tracker = $this->collection->addTracker('Test', '555');

        $this->tracker = new Tracker('555');
        $this->tracker->setTitle('Test');
    }

    protected function tearDown()
    {
    }

    public function testIsEnabledByDefault ()
    {
        $this->assertTrue($this->collection->enabled());
    }

    public function testCollectionContainsTrackerObjects ()
    {
        $this->assertContains($this->tracker, $this->collection->getTrackers());
    }

    public function testAddTrackerReturnsTrackerObject ()
    {
        $this->assertEquals($this->tracker, $this->object->addTracker('Test', '555'));
    }



}
