<?php
namespace SlmGoogleAnalytics\Analytics;

use \PHPUnit_Framework_TestCase as TestCase;
use SlmGoogleAnalytics\Analytics\Collection as Collection;
use SlmGoogleAnalytics\Analytics\Tracker as Tracker;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-15 at 13:54:17.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Collection
     */
    protected $object;

    /**
     * @var Tracker
     */
    protected $child;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Collection;
        $this->child = new Tracker('UA-55555-5');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

}
